import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
        antialiased !bg-red-300 border-2 border-black min-h-screen
        flex flex-col`}
      >
        <header>
          <nav className="flex gap-4">
            <Link href="/">Home</Link>
            <Link href="/list">List</Link>
          </nav>
        </header>
        <main className="flex-grow flex justify-center items-center">{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
